export const keyboardRegex = /[a-z0-9\t\n /<>?;:"'`!@#$%^&*()[\]{}_+=|\\-]/gm

export const specialKeys: { [key: string]: string } = {
  control: 'ctrl',
  shift: 'shift',
  alt: 'alt',
  option: 'option',
  command: 'command',
  meta: 'meta',
  backspace: 'backspace',
  tab: 'tab',
  enter: 'enter',
  return: 'return',
  capslock: 'capslock',
  esc: 'esc',
  escape: 'escape',
  space: 'space',
  pageup: 'pageup',
  pagedown: 'pagedown',
  end: 'end',
  home: 'home',
  arrowup: 'up',
  arrowright: 'right',
  arrowleft: 'left',
  arrowdown: 'down',
  insert: 'ins',
  delete: 'del',
  plus: 'plus',
}

export const windowsShortcuts = [
  'ctrl+n',
  'ctrl+c',
  'ctrl+v',
  'ctrl+shift+n',
  'ctrl+t',
  'ctrl+shift+t',
  'ctrl+tab',
  'ctrl+escape',
  'ctrl+pagedown',
  'ctrl+shift+tab',
  'ctrl+pageup',
  'ctrl+1',
  'ctrl+2',
  'ctrl+3',
  'ctrl+4',
  'ctrl+5',
  'ctrl+6',
  'ctrl+7',
  'ctrl+8',
  'ctrl+9',
  'alt+home',
  'alt+arrowleft',
  'alt+arrowright',
  'ctrl+w',
  'ctrl+f4',
  'ctrl+shift+w',
  'alt+f4',
  'alt+space+n',
  'alt+space+x',
  'alt+f+x',
  'ctrl+arrowright',
  'ctrl+arrowleft',
  'alt+f',
  'alt+e',
  'ctrl+shift+b',
  'ctrl+shift+o',
  'ctrl+h',
  'ctrl+j',
  'shift+escape',
  'shift+alt+t',
  'f1',
  'f3',
  'f5',
  'f6',
  'f7',
  'f10',
  'f11',
  'f12',
  'ctrl+f',
  'ctrl+g',
  'ctrl+shift+g',
  'ctrl+shift+j',
  'ctrl+shift+delete',
  'ctrl+shift+m',
  'alt+shift+i',
  'ctrl+f6',
  'alt+shift+a',
  'ctrl+p',
  'ctrl+s',
  'ctrl+r',
  'escape',
  'tab',
  'shift+tab',
  'ctrl+o',
  'ctrl+u',
  'ctrl+d',
  'ctrl+shift+d',
  'ctrl++',
  'ctrl+-',
  'ctrl+0',
  'space',
  'pagedown',
  'shift+space',
  'pageup',
  'home',
  'end',
  'ctrl+arrowleft',
  'ctrl+arrowright',
  'ctrl+backspace',
  'alt+home',
]

export const macShortcuts = [
  'meta+n',
  'meta+c',
  'meta+v',
  'meta+a',
  'meta+r',
  'meta+shift+n',
  'meta+t',
  'meta+shift+t',
  'meta+alt+arrowright',
  'meta+alt+arrowleft',
  'meta+1',
  'meta+2',
  'meta+3',
  'meta+4',
  'meta+5',
  'meta+6',
  'meta+7',
  'meta+8',
  'meta+9',
  'meta+[',
  'meta+]',
  'meta+arrowleft',
  'meta+arrowright',
  'meta+w',
  'meta+shift+w',
  'meta+m',
  'meta+h',
  'meta+q',
  'meta+arrowright',
  'meta+arrowleft',
  'meta+shift+b',
  'meta+alt+b',
  'meta+,',
  'meta+y',
  'meta+shift+j',
  'meta+f',
  'meta+g',
  'meta+shift+g',
  'meta+e',
  'meta+alt+i',
  'meta+shift+delete',
  'meta+shift+m',
  'ctrl+f2',
  'meta+alt+arrowup',
  'meta+alt+shift+i',
  'f7',
  'f11',
  'f12',
  'meta+alt+shift+a',
  'meta+p',
  'meta+s',
  'meta+alt+p',
  'meta+shift+r',
  'escape',
  'tab',
  'shift+tab',
  'meta+o',
  'meta+alt+u',
  'meta+alt=j',
  'meta+d',
  'meta+shift+d',
  'meta+ctrl+f',
  'meta++',
  'meta+-',
  'meta+0',
  'space',
  'shift+space',
  'meta+alt+f',
  'alt+arrowleft',
  'alt+arrowright',
  'alt+delete',
  'meta+shift+h',
  'meta+0',
]
