export type Pack = {
  id: number
  name: string
  description: string
  artist: string
  urls: string[]
}

export enum PackName {
  ASTRO = 'astrobunny',
  GRIM = 'grimreaper',
  MARSH = 'marshmellow',
  FOOD = 'food',
  BLACKCAT = 'blackcat',
  GENSHIN = 'genshin',
  GENSHIN2 = 'genshin2',
  STARWARS = 'starwars',
  BIRDS = 'birds',
}

export const Glyphs: Record<PackName, Pack> = {
  astrobunny: {
    id: 1,
    name: 'Astrobunny',
    description: 'Short description can go here. Lorem ipsum.',
    artist: 'John Treanor',
    urls: [
      `glyphs/astrobunny/$1/AHH.gif`,
      `glyphs/astrobunny/$1/AHHcloseup.gif`,
      `glyphs/astrobunny/$1/Coy_02.gif`,
      `glyphs/astrobunny/$1/Cry.gif`,
      `glyphs/astrobunny/$1/Cry2.gif`,
      `glyphs/astrobunny/$1/Laugh.webp`,
      `glyphs/astrobunny/$1/Luv.gif`,
      `glyphs/astrobunny/$1/Luv_02.gif`,
      `glyphs/astrobunny/$1/Sad3.gif`,
      `glyphs/astrobunny/$1/ThumbsDownNew.gif`,
      `glyphs/astrobunny/$1/ThumbsUP.gif`,
      `glyphs/astrobunny/$1/ThumbsUPNew.gif`,
    ],
  },
  grimreaper: {
    id: 2,
    name: 'Grim Reaper',
    description: 'Short description can go here. Lorem ipsum.',
    artist: 'LAM',
    urls: [
      `glyphs/grim_reaper/$1/1.webp`,
      `glyphs/grim_reaper/$1/2.webp`,
      `glyphs/grim_reaper/$1/3.webp`,
      `glyphs/grim_reaper/$1/4.webp`,
      `glyphs/grim_reaper/$1/5.webp`,
      `glyphs/grim_reaper/$1/6.webp`,
    ],
  },
  marshmellow: {
    id: 3,
    name: 'Marshmello',
    description: 'Short description can go here. Lorem ipsum.',
    artist: 'John Treanor',
    urls: [
      `glyphs/marshmello/$1/Ahhhhh.gif`,
      `glyphs/marshmello/$1/Emoji_01.webp`,
      `glyphs/marshmello/$1/Emoji_02.webp`,
      `glyphs/marshmello/$1/Emoji_03.webp`,
      `glyphs/marshmello/$1/Emoji_04.webp`,
      `glyphs/marshmello/$1/Emoji_05.webp`,
      `glyphs/marshmello/$1/Emoji_06.webp`,
      `glyphs/marshmello/$1/Emoji_07.webp`,
      `glyphs/marshmello/$1/Emoji_08.webp`,
      `glyphs/marshmello/$1/Emoji_09.webp`,
      `glyphs/marshmello/$1/Emoji_10.webp`,
      `glyphs/marshmello/$1/Emoji_11.webp`,
      `glyphs/marshmello/$1/Emoji_12.webp`,
      `glyphs/marshmello/$1/Emoji_13.webp`,
      `glyphs/marshmello/$1/HellYea.gif`,
      `glyphs/marshmello/$1/Luv.gif`,
      `glyphs/marshmello/$1/spark.gif`,
    ],
  },
  food: {
    id: 4,
    name: 'Food',
    description: 'Short description can go here. Lorem ipsum.',
    artist: 'Lya',
    urls: [
      `glyphs/lya/$1/Beer.gif`,
      `glyphs/lya/$1/Toast.gif`,
      `glyphs/lya/$1/chocolate_angry.gif`,
      `glyphs/lya/$1/chocolate_cute.gif`,
      `glyphs/lya/$1/coconut_cute.gif`,
      `glyphs/lya/$1/coconut_rude.gif`,
      `glyphs/lya/$1/coffee_cute.gif`,
      `glyphs/lya/$1/coffee_rude.gif`,
      `glyphs/lya/$1/croissant2.gif`,
      `glyphs/lya/$1/croissant1.gif`,
      `glyphs/lya/$1/fries.gif`,
      `glyphs/lya/$1/onigiri.gif`,
    ],
  },
  blackcat: {
    id: 5,
    name: 'Black Cat',
    description: 'Short description can go here. Lorem ipsum.',
    artist: 'Dan Tavis',
    urls: [
      `glyphs/black_cat/$1/Black-Cat-Attention-2.webp`,
      `glyphs/black_cat/$1/Cat-+-Flowers.webp`,
      `glyphs/black_cat/$1/Cat-Vs-Yarn-%28cover%29.webp`,
      `glyphs/black_cat/$1/Fluff.webp`,
      `glyphs/black_cat/$1/Sleep-Day%20%284%29.webp`,
      `glyphs/black_cat/$1/Thumbs-Up-Cat.webp`,
    ],
  },
  genshin: {
    id: 6,
    name: 'Genshin Impact 1',
    description: 'Short description can go here. Lorem ipsum.',
    artist: 'John Treanor',
    urls: [
      `glyphs/genshin_1/$1/JohnTreanor_GenshinImpactFood_01.webp`,
      `glyphs/genshin_1/$1/JohnTreanor_GenshinImpactFood_02.webp`,
      `glyphs/genshin_1/$1/JohnTreanor_GenshinImpactFood_03.webp`,
      `glyphs/genshin_1/$1/JohnTreanor_GenshinImpactFood_04.webp`,
      `glyphs/genshin_1/$1/JohnTreanor_GenshinImpactFood_05.webp`,
      `glyphs/genshin_1/$1/JohnTreanor_GenshinImpactFood_06.webp`,
      `glyphs/genshin_1/$1/JohnTreanor_GenshinImpactFood_07.webp`,
      `glyphs/genshin_1/$1/JohnTreanor_GenshinImpactFood_08.webp`,
      `glyphs/genshin_1/$1/JohnTreanor_GenshinImpactFood_09.webp`,
      // `glyphs/genshin_1/$1/JohnTreanor_GenshinImpactFood_22.webp`,
      // `glyphs/genshin_1/$1/JohnTreanor_GenshinImpactFood_23.webp`,
    ],
  },
  genshin2: {
    id: 7,
    name: 'Genshin Impact 2',
    description: 'Short description can go here. Lorem ipsum.',
    artist: 'John Treanor',
    urls: [
      `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_10.webp`,
      `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_11.webp`,
      `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_12.webp`,
      `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_13.webp`,
      `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_14.webp`,
      `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_15.webp`,
      `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_16.webp`,
      `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_17.webp`,
      `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_18.webp`,
      `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_19.webp`,
      `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_20.webp`,
      `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_21.webp`,
      // `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_22.webp`,
      // `glyphs/genshin_2/$1/JohnTreanor_GenshinImpactFood_23.webp`,
    ],
  },
  starwars: {
    id: 8,
    name: 'Star Wars',
    description: 'Short description can go here. Lorem ipsum.',
    artist: 'John Treanor',
    urls: [
      `glyphs/star_wars/$1/JohnTreanor_StarWarsPack_01.webp`,
      `glyphs/star_wars/$1/JohnTreanor_StarWarsPack_02.webp`,
      `glyphs/star_wars/$1/JohnTreanor_StarWarsPack_03.webp`,
      `glyphs/star_wars/$1/JohnTreanor_StarWarsPack_04.webp`,
      `glyphs/star_wars/$1/JohnTreanor_StarWarsPack_05.webp`,
      `glyphs/star_wars/$1/JohnTreanor_StarWarsPack_06.webp`,
      `glyphs/star_wars/$1/JohnTreanor_StarWarsPack_07.webp`,
      `glyphs/star_wars/$1/JohnTreanor_StarWarsPack_08.webp`,
      `glyphs/star_wars/$1/JohnTreanor_StarWarsPack_09.webp`,
    ],
  },
  birds: {
    id: 9,
    name: 'Birds',
    description: 'Short description can go here. Lorem ipsum.',
    artist: 'Dina Brodsky',
    urls: [
      `glyphs/birds/$1/hawk.webp`,
      `glyphs/birds/$1/ducklings.webp`,
      `glyphs/birds/$1/owl.webp`,
      `glyphs/birds/$1/penguins.webp`,
      `glyphs/birds/$1/robin.webp`,
      `glyphs/birds/$1/stork.webp`,
      `glyphs/birds/$1/yellow_bird.webp`,
    ],
  },
}
