import {
  UIState,
  GlyphMarketViewStatus,
  Themes,
  Flairs,
  SettingsRoutes,
} from './types'

const InitialUIState = (): UIState => ({
  contextMenuStatus: false,
  showSidebarUsers: true,
  showSidebar: true,
  showSearchResult: false,
  showSettings: false,
  showMedia: false,
  settingsSideBar: true,
  settingsRoute: SettingsRoutes.PERSONALIZE,
  quickProfile: false,
  userProfile: {},
  contextMenuValues: [],
  contextMenuPosition: { x: 0, y: 0 },
  quickProfilePosition: { x: 0, y: 0 },
  modals: {
    newfolder: false,
    createServer: false,
    marketplace: false,
    wallet: false,
    quickchat: false,
    creategroup: false,
    walletMini: false,
    error: false,
    changelog: false,
    glyph: false,
    userProfile: false,
    groupInvite: { isOpen: false },
    callToAction: false,
    renameFile: false,
  },
  glyphModalPack: '',
  chatbarContent: '',
  replyChatbarContent: { id: '', from: '', payload: '' },
  chatbarFocus: false,
  fullscreen: false,
  showPinned: false,
  enhancers: {
    show: false,
    floating: false,
    position: [0, 0],
    defaultWidth: '24rem',
    defaultHeight: '30rem',
    containerWidth: 0,
    route: 'emotes',
  },
  messages: [],
  unreadMessage: 0,
  isScrollOver: false,
  isTyping: false,
  isReacted: false,
  activeChannel: undefined,
  settingReaction: { status: false, groupID: null, messageID: null },
  hoveredGlyphInfo: undefined,
  glyphMarketplaceView: {
    view: GlyphMarketViewStatus.HOME,
    shopId: null,
  },
  editMessage: { id: '', from: '', payload: '' },
  recentReactions: ['👍', '😂', '♥️'],
  mostEmojiUsed: [],
  recentGlyphs: [],
  theme: {
    base: Themes[0],
    flair: Flairs[0],
  },
  isLoadingFileIndex: false,
  renamingItem: undefined,
})

export default InitialUIState
