name: 'Build Desktop App'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
  APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
  APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
  APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
  APPLE_ID: ${{ secrets.APPLE_ID }}
  APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  publish-tauri:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest]

    runs-on: ${{ matrix.platform }}
    if: always()
    steps:
      - name: Checkout 🔖
        uses: actions/checkout@v2

      - name: Setup Node.js 🔨
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Change permissions on scripts 🔨
        run: chmod +x ./linkscript.sh
      - name: Yarn config 🔨
        run: yarn config set network-timeout 600000 -g
      - name: Build Core 🔨
        run: ./linkscript.sh && yarn && yarn generate
      - name: install Rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Tauri build 🔨
        run: yarn tauri build
      - name: Codesign executable
        env:
          MACOS_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 —decode > certificate.p12
          security create-keychain -p test001 build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p test001 build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k test001 build.keychain
          /usr/bin/codesign --force -s <identity-id> ./src-tauri/target/release/bundle/dmg/Satellite Core_0.2.1_aarch64.dmg
      - name: Upload dmg 🔨
        uses: actions/upload-artifact@v2
        with:
          name: dmg
          path: src-tauri/target/release/bundle/dmg/Satellite Core_0.2.1_aarch64.dmg
