name: Cypress Second Action

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  cypress:
    name: Cypress 2
    runs-on: ubuntu-20.04

    container:
      image: cypress/browsers:node16.13.0-chrome95-ff94
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create env file - core
        run: |
          touch .env
          echo ENVIRONMENT="dev" >> .env
          echo NUXT_ENV_IRIDIUM_SYNC_NODES=${{ secrets.NUXT_ENV_IRIDIUM_SYNC_NODES }} >> .env
          echo NUXT_ENV_IRIDIUM_APIS=${{ secrets.NUXT_ENV_IRIDIUM_APIS }} >> .env
          echo NUXT_ENV_IRIDIUM_GATEWAYS=${{ secrets.NUXT_ENV_IRIDIUM_GATEWAYS }} >> .env
          cat .env

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.12.2
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"

      - name: Cache for CorePWA
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Sync Node
        working-directory: ./
        run: sh ./build-script.sh &

      - name: Cypress tests with debug logs
        uses: cypress-io/github-action@v4
        env:
          DEBUG: '@cypress/github-action'
        with:
          start: yarn dev
          working-directory: ./
          command: npx cypress run --browser chrome
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 300

      - name: Artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
