name: Cypress Second Action

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  cypress:
    name: Cypress 2
    runs-on: ubuntu-20.04

    container:
      image: cypress/browsers:node16.13.0-chrome95-ff94
      options: --user 1001

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create env file - iridium
        run: |
          cd ..
          cd iridium
          echo HOSTNAME=${{ secrets.HOSTNAME }} >> .env
          echo CERTBOT_EMAIL="support@satellite.im" >> .env
          echo SYNC_NODE_SEED="sync node a seed" >> .env
          echo SYNC_NODE_ADDR=${{ secrets.SYNC_NODE_ADDR }} >> .env
          echo SERVERDATAVOLUME=${{ secrets.SERVERDATAVOLUME }} >> .env
          echo NODE_ENV="development" >> .env
          echo SAFER_URL=${{ secrets.SAFER_URL }} >> .env
          cat .env

      - name: Create env file - core
        run: |
          touch .env
          echo ENVIRONMENT="dev" >> .env
          echo NUXT_ENV_IRIDIUM_SYNC_NODES=${{ secrets.NUXT_ENV_IRIDIUM_SYNC_NODES }} >> .env
          echo NUXT_ENV_IRIDIUM_APIS=${{ secrets.NUXT_ENV_IRIDIUM_APIS }} >> .env
          echo NUXT_ENV_IRIDIUM_GATEWAYS=${{ secrets.NUXT_ENV_IRIDIUM_GATEWAYS }} >> .env
          cat .env

      - name: Yarn Install
        run: yarn install

      - name: Pnpm build and watch
        working-directory: ./
        run: |
          cd ..
          cd iridium
          pnpm i
          pnpm watch &

      - name: Sync Node
        working-directory: ./
        run: cd ..
          cd iridium
          pnpm sync-node &

      - name: Yarn Link
        run: yarn link "@satellite-im/iridium"

      - name: Cypress tests with debug logs
        uses: cypress-io/github-action@v4
        env:
          DEBUG: '@cypress/github-action'
        with:
          start: yarn dev
          working-directory: ./
          command: npx cypress run --browser chrome
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 300

      - name: Artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
