name: Cypress Second Action

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  cypress:
    name: Cypress 2
    runs-on: ubuntu-20.04
    container: cypress/included:10.8.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js 🔨
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Yarn Cache
        uses: actions/cache@v3
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Cache Cypress binary
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-

      - name: Clone Iridium Repo
        run: |
          cd ..
          git clone https://github.com/Satellite-im/iridium.git

      - name: Create env file - iridium
        run: |
          cd ..
          cd iridium
          echo HOSTNAME=${{ secrets.HOSTNAME }} >> .env
          echo CERTBOT_EMAIL="support@satellite.im" >> .env
          echo SYNC_NODE_SEED="sync node a seed" >> .env
          echo SYNC_NODE_ADDR=${{ secrets.SYNC_NODE_ADDR }} >> .env
          echo SERVERDATAVOLUME=${{ secrets.SERVERDATAVOLUME }} >> .env
          echo NODE_ENV="development" >> .env
          echo SAFER_URL=${{ secrets.SAFER_URL }} >> .env
          cat .env

      - name: Create env file - core
        working-directory: ./
        run: |
          touch .env
          echo ENVIRONMENT="dev" >> .env
          echo NUXT_ENV_IRIDIUM_SYNC_NODES=${{ secrets.NUXT_ENV_IRIDIUM_SYNC_NODES }} >> .env
          echo NUXT_ENV_IRIDIUM_APIS=${{ secrets.NUXT_ENV_IRIDIUM_APIS }} >> .env
          echo NUXT_ENV_IRIDIUM_GATEWAYS=${{ secrets.NUXT_ENV_IRIDIUM_GATEWAYS }} >> .env
          cat .env

      - name: Run Linkscript
        run: |
          chmod +x ./linkscript.sh
          ./linkscript.sh

      - name: Yarn
        run: yarn

      - name: Pnpm i
        working-directory: ../iridium
        run: pnpm i

      - name: Cypress tests with debug logs
        uses: cypress-io/github-action@v4
        env:
          DEBUG: '@cypress/github-action'
        with:
          install: false
          start: |
            # Execute PNPM Watch in the background
            cd .. && cd iridium && pwd && pnpm watch &
            # Execute PNPM Sync Node in the background
            cd .. && cd iridium && pwd && pnpm sync-node &
            # Yarn Link Iridium repo
            yarn link "@satellite-im/iridium"
            # Printing cypress info
            npx cypress info
            # List of files from CorePWA repo
            pwd && ls -la
            # List of files from Iridium repo
            cd .. && cd iridium && pwd && ls -la && cd ..
            # List of spec files from Cypress
            cd cypress/e2e && pwd && ls -la && cd ../..
            # Start server
            yarn dev
          browser: chrome
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 300
          spec: cypress/e2e/add-friend.js
          config-file: cypress.config.js

      - name: Artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
