name: eslint
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn
        run: yarn
      - name: eslint
        uses: tj-actions/eslint-changed-files@v14
      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{ts,vue,html}
          only_changed: true
