name: eslint-prettier
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  eslint-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yarn
        run: yarn
      - name: eslint
        uses: tj-actions/eslint-changed-files@v14
      - name: prettier
      - uses: EPMatt/reviewdog-action-prettier@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: warning
