name: Jest Coverage

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - name: JEST Report
      uses: RedaktionsNetzwerk-Deutschland/action-jest-reporter@v1.0.0
