name: Comment test coverage
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
    coverage:
        permissions:
          checks: write
          pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - uses: ArtiomTr/jest-coverage-report-action@v2
