name: Comment test coverage
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: raulanatol/jest-coverage-comment-action@main
         with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jest-command: 'yarn test jest-ci'
