name: Comment test coverage
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: raulanatol/jest-coverage-comment-action@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}'
