name: Linter
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - name: Prettier
      run: yarn prettier .
    - name: ESLint
      run: yarn eslint --fix .
      
