name: Require Checklist
on:
  pull_request:
    types: [opened, edited, synchronize]
  issues:
    types: [opened, edited, deleted]
jobs:
  job1:
    runs-on: ubuntu-16.04
    steps:
      - uses: mheap/require-checklist-action@v1
        with:
          requireChecklist: false # If this is true and there are no checklists detected, the action will fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
