name: Require Checklist
on:
  pull_request:
    types: [opened, edited, synchronize]
  issues:
    types: [opened, edited, deleted]
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: test001
      - uses: mheap/require-checklist-action@v1
        with:
          requireChecklist: false # If this is true and there are no checklists detected, the action will fail
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Comment on Issue
        uses: ActionsDesk/add-comment-action@master
        with:
           message: ${{ steps.invite_user.outputs.message }}
           failureMessage: ${{ steps.invite_user.outputs.message }}
        
