on:
  issue_comment:
    types: [opened]

jobs:
  prettier:
    runs-on: ubuntu-latest
    name: Run Prettier
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN }}

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: 'npm'

      - run: npm ci

      - name: run prettier command
        uses: ykpythemind/run_prettier_action@v1
        with:
          prettier_command: ./node_modules/.bin/prettier --write
          GITHUB_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply prettier changes
          skip_fetch: true
