name: Prettier

on:
  pull_request:
    paths-ignore:
      - README.md
      - .github/workflows/prettier.yml

jobs:
  cleanup_tasks:
    runs-on: ubuntu-latest

    steps:
    - name: Cloning the repository
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Prettify the Code
      uses: lwerner-lshigh/prettier_action_java@v1.1.1
      with:
        prettier_options: '--no-semi --write .'
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
