name: Prettier

on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Prettify code
      uses: creyD/prettier_action@v3.1
      with:
        prettier_options: --write .
        only_changed: True
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
