name: Prettier

on:
  pull_request:

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: eduardbme/eduardbme/github-action-prettier@2.3.2
        with:
         args: . --check 
