name: Run Jest tests
on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pnpm
        run: brew install pnpm
      - name: Install modules
        run: yarn install --network-concurrency 1
      - name: Run tests
        run: yarn test
